### ISSUE TITLE
Bug  CLASSIFICATION_ENDPOINT

### ISSUE THREAD

**Issue by wannaphongcom** [monkeylearn/monkeylearn-python#5]
```python
>>> from monkeylearn import MonkeyLearn
>>> ml = MonkeyLearn('API')
>>> res = ml.classifiers.create('Test Classifier')
>>> module_id = res.result['classifier']['hashed_id']
>>> res = ml.classifiers.detail(module_id)
>>> root_id = res.result['sandbox_categories'][0]['id']
>>> res = ml.classifiers.categories.create(module_id, 'Negative', root_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\monkeylearn\classification.py", line 20, in ca
tegories
    return Categories(self.token)
  File "C:\py34\lib\site-packages\monkeylearn\classification.py", line 110, in _
_init__
    self.endpoint = CLASSIFICATION_ENDPOINT
NameError: name 'CLASSIFICATION_ENDPOINT' is not defined
```
I using Python 3.4.3 64 bit for windows. Thank you.

**Comment by wannaphongcom** [comment]
fix https://github.com/monkeylearn/monkeylearn-python/pull/6

**Comment by rsteca** [comment]
Solved, thanks for reporting
