### ISSUE TITLE
bug Resource not found

### ISSUE THREAD

**Issue by wannaphongcom** [monkeylearn/monkeylearn-python#7]
I doing like https://github.com/monkeylearn/monkeylearn-python but , It's have bug.
```python
>>> from monkeylearn import MonkeyLearn
>>> ml = MonkeyLearn('API')
>>> res = ml.classifiers.create('Test Classifier')
>>> module_id = res.result['classifier']['hashed_id']
>>> res = ml.classifiers.detail(module_id)
>>> root_id = res.result['sandbox_categories'][0]['id']
>>> res = ml.classifiers.categories.create(module_id, 'Negative', root_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\py34\lib\site-packages\monkeylearn\classification.py", line 119, in c
reate
    self.handle_errors(response)
  File "C:\py34\lib\site-packages\monkeylearn\utils.py", line 78, in handle_erro
rs
    raise MonkeyLearnException(json.dumps(res['detail']))
monkeylearn.exceptions.MonkeyLearnException: Error: "Resource not found. Check y
our URL."
```

**Comment by rsteca** [comment]
Solved, thanks for reporting
